# Generated by Django 2.1.1 on 2019-02-16 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên item')),
                ('stt', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_img/download_item', verbose_name='Ảnh')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['stt', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadSymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Symbol')),
                ('stt', models.IntegerField(blank=True, null=True)),
                ('link_6_months', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link 6 tháng')),
                ('link_1_year', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link 1 năm')),
                ('link_2_years', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link 2 năm')),
                ('link_5_years', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link 5 năm')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.DownloadItem')),
            ],
            options={
                'ordering': ['stt', '-updated_at'],
            },
        ),
    ]
