# Generated by Django 2.1.1 on 2019-02-16 08:01

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tên')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo mới')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
            ],
            options={
                'verbose_name': 'Danh mục blog',
                'verbose_name_plural': 'Danh mục blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Tác giả')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo mới')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('content', models.TextField(max_length=2000, verbose_name='Nội dung')),
                ('allow', models.BooleanField(blank=True, default=True, verbose_name='Cho phép')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo mới')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Tác giả')),
                ('hashtag', models.CharField(blank=True, max_length=500)),
                ('main_img', models.ImageField(blank=True, upload_to=blog.models.upload_image_path, verbose_name='Ảnh blog')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Nội dung')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogCategory', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Bài blog',
                'verbose_name_plural': 'Bài blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost', verbose_name='Bài blog'),
        ),
    ]
