# Generated by Django 2.1.1 on 2019-02-16 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(max_length=150, verbose_name='Địa chỉ')),
                ('note', models.TextField(blank=True, verbose_name='Chú thích')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('delivered', models.BooleanField(default=False, verbose_name='Giao hàng')),
                ('paid', models.BooleanField(default=False, verbose_name='Thanh toán')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thành tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.ForexProduct', verbose_name='Sản phẩm')),
            ],
        ),
    ]
