# Generated by Django 2.1.1 on 2019-02-16 07:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForexProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Thời hạn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='forex_products')),
                ('note', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Ghi chú')),
                ('price', models.IntegerField(verbose_name='Giá')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
    ]
