# Generated by Django 2.1.1 on 2019-02-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forexproduct',
            options={'ordering': ['stt', '-updated_at'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AddField(
            model_name='forexproduct',
            name='stt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
